name: SideloadStore
options:
  bundleIdPrefix: dev.pavel
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

targets:
  SideloadStore:
    type: application
    platform: iOS
    sources:
      - path: App/Sources
      - path: App/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.pavel.sideloadstore
        PRODUCT_NAME: SideloadStore
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
